# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BivariateChoropleth
                                 A QGIS plugin
 Bivariate Choropleth Maps
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-10-25
        copyright            : (C) 2019 by Joost Neujens
        email                : jneujens@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BivariateChoropleth class from file BivariateChoropleth.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .bivariate_choropleth import BivariateChoropleth
    return BivariateChoropleth(iface)
